stages:
  - deploy

deploy_to_vercel:
  stage: deploy
  image: node:latest
  before_script:
    - npm install -g vercel
  script:
    - vercel --version
    - vercel deploy --prod --yes --token=$VERCEL_TOKEN 
  only:
    - master