stages:
  - deploy

deploy_to_vercel:
  stage: deploy
  image: node:latest
  before_script:
    - npm install -g vercel 
  script:
    - vercel --version 
    - vercel --prod --token=$VERCEL_TOKEN 
  only:
    - master
